// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: sistema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pirata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Recompensa    int32                  `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	Peligrosidad  string                 `protobuf:"bytes,4,opt,name=peligrosidad,proto3" json:"peligrosidad,omitempty"` // "bajo", "medio", "alto"
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`             // "buscado", "capturado", "entregado", "perdido"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pirata) Reset() {
	*x = Pirata{}
	mi := &file_sistema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pirata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pirata) ProtoMessage() {}

func (x *Pirata) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pirata.ProtoReflect.Descriptor instead.
func (*Pirata) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{0}
}

func (x *Pirata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pirata) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Pirata) GetRecompensa() int32 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

func (x *Pirata) GetPeligrosidad() string {
	if x != nil {
		return x.Peligrosidad
	}
	return ""
}

func (x *Pirata) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type ListaPiratas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piratas       []*Pirata              `protobuf:"bytes,1,rep,name=piratas,proto3" json:"piratas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaPiratas) Reset() {
	*x = ListaPiratas{}
	mi := &file_sistema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaPiratas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaPiratas) ProtoMessage() {}

func (x *ListaPiratas) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaPiratas.ProtoReflect.Descriptor instead.
func (*ListaPiratas) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{1}
}

func (x *ListaPiratas) GetPiratas() []*Pirata {
	if x != nil {
		return x.Piratas
	}
	return nil
}

type ResultadoOperacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoOperacion) Reset() {
	*x = ResultadoOperacion{}
	mi := &file_sistema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoOperacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoOperacion) ProtoMessage() {}

func (x *ResultadoOperacion) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoOperacion.ProtoReflect.Descriptor instead.
func (*ResultadoOperacion) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{2}
}

func (x *ResultadoOperacion) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoOperacion) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type EstadoGlobalResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarinaCounter   int32                  `protobuf:"varint,1,opt,name=marinaCounter,proto3" json:"marinaCounter,omitempty"`
	SubmundoCounter int32                  `protobuf:"varint,2,opt,name=submundoCounter,proto3" json:"submundoCounter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstadoGlobalResponse) Reset() {
	*x = EstadoGlobalResponse{}
	mi := &file_sistema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoGlobalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoGlobalResponse) ProtoMessage() {}

func (x *EstadoGlobalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoGlobalResponse.ProtoReflect.Descriptor instead.
func (*EstadoGlobalResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{3}
}

func (x *EstadoGlobalResponse) GetMarinaCounter() int32 {
	if x != nil {
		return x.MarinaCounter
	}
	return 0
}

func (x *EstadoGlobalResponse) GetSubmundoCounter() int32 {
	if x != nil {
		return x.SubmundoCounter
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_sistema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{4}
}

type CapturaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdCazarrecompensas string                 `protobuf:"bytes,1,opt,name=idCazarrecompensas,proto3" json:"idCazarrecompensas,omitempty"`
	Pirata             *Pirata                `protobuf:"bytes,2,opt,name=pirata,proto3" json:"pirata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CapturaRequest) Reset() {
	*x = CapturaRequest{}
	mi := &file_sistema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturaRequest) ProtoMessage() {}

func (x *CapturaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturaRequest.ProtoReflect.Descriptor instead.
func (*CapturaRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{5}
}

func (x *CapturaRequest) GetIdCazarrecompensas() string {
	if x != nil {
		return x.IdCazarrecompensas
	}
	return ""
}

func (x *CapturaRequest) GetPirata() *Pirata {
	if x != nil {
		return x.Pirata
	}
	return nil
}

type ConfirmarEntregaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdCazarrecompensas string                 `protobuf:"bytes,1,opt,name=idCazarrecompensas,proto3" json:"idCazarrecompensas,omitempty"`
	Pirata             *Pirata                `protobuf:"bytes,2,opt,name=pirata,proto3" json:"pirata,omitempty"`
	Destino            string                 `protobuf:"bytes,3,opt,name=destino,proto3" json:"destino,omitempty"` // "Marina" o "Submundo"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfirmarEntregaRequest) Reset() {
	*x = ConfirmarEntregaRequest{}
	mi := &file_sistema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmarEntregaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmarEntregaRequest) ProtoMessage() {}

func (x *ConfirmarEntregaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmarEntregaRequest.ProtoReflect.Descriptor instead.
func (*ConfirmarEntregaRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmarEntregaRequest) GetIdCazarrecompensas() string {
	if x != nil {
		return x.IdCazarrecompensas
	}
	return ""
}

func (x *ConfirmarEntregaRequest) GetPirata() *Pirata {
	if x != nil {
		return x.Pirata
	}
	return nil
}

func (x *ConfirmarEntregaRequest) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type ReputacionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdCazarrecompensas string                 `protobuf:"bytes,1,opt,name=idCazarrecompensas,proto3" json:"idCazarrecompensas,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReputacionRequest) Reset() {
	*x = ReputacionRequest{}
	mi := &file_sistema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputacionRequest) ProtoMessage() {}

func (x *ReputacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputacionRequest.ProtoReflect.Descriptor instead.
func (*ReputacionRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{7}
}

func (x *ReputacionRequest) GetIdCazarrecompensas() string {
	if x != nil {
		return x.IdCazarrecompensas
	}
	return ""
}

type ReputacionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Reputacion       int32                  `protobuf:"varint,1,opt,name=reputacion,proto3" json:"reputacion,omitempty"`
	EntregasMarina   int32                  `protobuf:"varint,2,opt,name=entregasMarina,proto3" json:"entregasMarina,omitempty"`     // Número de entregas a la Marina
	EntregasSubmundo int32                  `protobuf:"varint,3,opt,name=entregasSubmundo,proto3" json:"entregasSubmundo,omitempty"` // Número de entregas al Submundo
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReputacionResponse) Reset() {
	*x = ReputacionResponse{}
	mi := &file_sistema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputacionResponse) ProtoMessage() {}

func (x *ReputacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputacionResponse.ProtoReflect.Descriptor instead.
func (*ReputacionResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{8}
}

func (x *ReputacionResponse) GetReputacion() int32 {
	if x != nil {
		return x.Reputacion
	}
	return 0
}

func (x *ReputacionResponse) GetEntregasMarina() int32 {
	if x != nil {
		return x.EntregasMarina
	}
	return 0
}

func (x *ReputacionResponse) GetEntregasSubmundo() int32 {
	if x != nil {
		return x.EntregasSubmundo
	}
	return 0
}

type EstadoRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdCazarrecompensas string                 `protobuf:"bytes,1,opt,name=idCazarrecompensas,proto3" json:"idCazarrecompensas,omitempty"` // ID del cazarrecompensas que reporta
	Pirata             *Pirata                `protobuf:"bytes,2,opt,name=pirata,proto3" json:"pirata,omitempty"`                         // Información del pirata
	NuevoEstado        string                 `protobuf:"bytes,3,opt,name=nuevoEstado,proto3" json:"nuevoEstado,omitempty"`               // Nuevo estado del pirata
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EstadoRequest) Reset() {
	*x = EstadoRequest{}
	mi := &file_sistema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoRequest) ProtoMessage() {}

func (x *EstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoRequest.ProtoReflect.Descriptor instead.
func (*EstadoRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{9}
}

func (x *EstadoRequest) GetIdCazarrecompensas() string {
	if x != nil {
		return x.IdCazarrecompensas
	}
	return ""
}

func (x *EstadoRequest) GetPirata() *Pirata {
	if x != nil {
		return x.Pirata
	}
	return nil
}

func (x *EstadoRequest) GetNuevoEstado() string {
	if x != nil {
		return x.NuevoEstado
	}
	return ""
}

type EntregaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdCazarrecompensas string                 `protobuf:"bytes,1,opt,name=idCazarrecompensas,proto3" json:"idCazarrecompensas,omitempty"`
	Pirata             *Pirata                `protobuf:"bytes,2,opt,name=pirata,proto3" json:"pirata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EntregaRequest) Reset() {
	*x = EntregaRequest{}
	mi := &file_sistema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntregaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntregaRequest) ProtoMessage() {}

func (x *EntregaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntregaRequest.ProtoReflect.Descriptor instead.
func (*EntregaRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{10}
}

func (x *EntregaRequest) GetIdCazarrecompensas() string {
	if x != nil {
		return x.IdCazarrecompensas
	}
	return ""
}

func (x *EntregaRequest) GetPirata() *Pirata {
	if x != nil {
		return x.Pirata
	}
	return nil
}

type VentaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdCazarrecompensas string                 `protobuf:"bytes,1,opt,name=idCazarrecompensas,proto3" json:"idCazarrecompensas,omitempty"`
	Pirata             *Pirata                `protobuf:"bytes,2,opt,name=pirata,proto3" json:"pirata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VentaRequest) Reset() {
	*x = VentaRequest{}
	mi := &file_sistema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VentaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VentaRequest) ProtoMessage() {}

func (x *VentaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VentaRequest.ProtoReflect.Descriptor instead.
func (*VentaRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{11}
}

func (x *VentaRequest) GetIdCazarrecompensas() string {
	if x != nil {
		return x.IdCazarrecompensas
	}
	return ""
}

func (x *VentaRequest) GetPirata() *Pirata {
	if x != nil {
		return x.Pirata
	}
	return nil
}

var File_sistema_proto protoreflect.FileDescriptor

const file_sistema_proto_rawDesc = "" +
	"\n" +
	"\rsistema.proto\x12\asistema\"\x8c\x01\n" +
	"\x06Pirata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x05R\n" +
	"recompensa\x12\"\n" +
	"\fpeligrosidad\x18\x04 \x01(\tR\fpeligrosidad\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\"9\n" +
	"\fListaPiratas\x12)\n" +
	"\apiratas\x18\x01 \x03(\v2\x0f.sistema.PirataR\apiratas\"D\n" +
	"\x12ResultadoOperacion\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"f\n" +
	"\x14EstadoGlobalResponse\x12$\n" +
	"\rmarinaCounter\x18\x01 \x01(\x05R\rmarinaCounter\x12(\n" +
	"\x0fsubmundoCounter\x18\x02 \x01(\x05R\x0fsubmundoCounter\"\a\n" +
	"\x05Empty\"i\n" +
	"\x0eCapturaRequest\x12.\n" +
	"\x12idCazarrecompensas\x18\x01 \x01(\tR\x12idCazarrecompensas\x12'\n" +
	"\x06pirata\x18\x02 \x01(\v2\x0f.sistema.PirataR\x06pirata\"\x8c\x01\n" +
	"\x17ConfirmarEntregaRequest\x12.\n" +
	"\x12idCazarrecompensas\x18\x01 \x01(\tR\x12idCazarrecompensas\x12'\n" +
	"\x06pirata\x18\x02 \x01(\v2\x0f.sistema.PirataR\x06pirata\x12\x18\n" +
	"\adestino\x18\x03 \x01(\tR\adestino\"C\n" +
	"\x11ReputacionRequest\x12.\n" +
	"\x12idCazarrecompensas\x18\x01 \x01(\tR\x12idCazarrecompensas\"\x88\x01\n" +
	"\x12ReputacionResponse\x12\x1e\n" +
	"\n" +
	"reputacion\x18\x01 \x01(\x05R\n" +
	"reputacion\x12&\n" +
	"\x0eentregasMarina\x18\x02 \x01(\x05R\x0eentregasMarina\x12*\n" +
	"\x10entregasSubmundo\x18\x03 \x01(\x05R\x10entregasSubmundo\"\x8a\x01\n" +
	"\rEstadoRequest\x12.\n" +
	"\x12idCazarrecompensas\x18\x01 \x01(\tR\x12idCazarrecompensas\x12'\n" +
	"\x06pirata\x18\x02 \x01(\v2\x0f.sistema.PirataR\x06pirata\x12 \n" +
	"\vnuevoEstado\x18\x03 \x01(\tR\vnuevoEstado\"i\n" +
	"\x0eEntregaRequest\x12.\n" +
	"\x12idCazarrecompensas\x18\x01 \x01(\tR\x12idCazarrecompensas\x12'\n" +
	"\x06pirata\x18\x02 \x01(\v2\x0f.sistema.PirataR\x06pirata\"g\n" +
	"\fVentaRequest\x12.\n" +
	"\x12idCazarrecompensas\x18\x01 \x01(\tR\x12idCazarrecompensas\x12'\n" +
	"\x06pirata\x18\x02 \x01(\v2\x0f.sistema.PirataR\x06pirata2\x80\x03\n" +
	"\x0fGobiernoService\x12<\n" +
	"\x13ObtenerListaPiratas\x12\x0e.sistema.Empty\x1a\x15.sistema.ListaPiratas\x12Q\n" +
	"\x10ConfirmarEntrega\x12 .sistema.ConfirmarEntregaRequest\x1a\x1b.sistema.ResultadoOperacion\x12N\n" +
	"\x13ConsultarReputacion\x12\x1a.sistema.ReputacionRequest\x1a\x1b.sistema.ReputacionResponse\x12D\n" +
	"\x13ObtenerEstadoGlobal\x12\x0e.sistema.Empty\x1a\x1d.sistema.EstadoGlobalResponse\x12F\n" +
	"\x0fReporteDeEstado\x12\x16.sistema.EstadoRequest\x1a\x1b.sistema.ResultadoOperacion2\xa1\x01\n" +
	"\rMarinaService\x12L\n" +
	"\x14EntregarPirataMarina\x12\x17.sistema.EntregaRequest\x1a\x1b.sistema.ResultadoOperacion\x12B\n" +
	"\x13AlertaTraficoIlegal\x12\x0e.sistema.Empty\x1a\x1b.sistema.ResultadoOperacion2_\n" +
	"\x0fSubmundoService\x12L\n" +
	"\x16EntregarPirataSubmundo\x12\x15.sistema.VentaRequest\x1a\x1b.sistema.ResultadoOperacionB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_sistema_proto_rawDescOnce sync.Once
	file_sistema_proto_rawDescData []byte
)

func file_sistema_proto_rawDescGZIP() []byte {
	file_sistema_proto_rawDescOnce.Do(func() {
		file_sistema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sistema_proto_rawDesc), len(file_sistema_proto_rawDesc)))
	})
	return file_sistema_proto_rawDescData
}

var file_sistema_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sistema_proto_goTypes = []any{
	(*Pirata)(nil),                  // 0: sistema.Pirata
	(*ListaPiratas)(nil),            // 1: sistema.ListaPiratas
	(*ResultadoOperacion)(nil),      // 2: sistema.ResultadoOperacion
	(*EstadoGlobalResponse)(nil),    // 3: sistema.EstadoGlobalResponse
	(*Empty)(nil),                   // 4: sistema.Empty
	(*CapturaRequest)(nil),          // 5: sistema.CapturaRequest
	(*ConfirmarEntregaRequest)(nil), // 6: sistema.ConfirmarEntregaRequest
	(*ReputacionRequest)(nil),       // 7: sistema.ReputacionRequest
	(*ReputacionResponse)(nil),      // 8: sistema.ReputacionResponse
	(*EstadoRequest)(nil),           // 9: sistema.EstadoRequest
	(*EntregaRequest)(nil),          // 10: sistema.EntregaRequest
	(*VentaRequest)(nil),            // 11: sistema.VentaRequest
}
var file_sistema_proto_depIdxs = []int32{
	0,  // 0: sistema.ListaPiratas.piratas:type_name -> sistema.Pirata
	0,  // 1: sistema.CapturaRequest.pirata:type_name -> sistema.Pirata
	0,  // 2: sistema.ConfirmarEntregaRequest.pirata:type_name -> sistema.Pirata
	0,  // 3: sistema.EstadoRequest.pirata:type_name -> sistema.Pirata
	0,  // 4: sistema.EntregaRequest.pirata:type_name -> sistema.Pirata
	0,  // 5: sistema.VentaRequest.pirata:type_name -> sistema.Pirata
	4,  // 6: sistema.GobiernoService.ObtenerListaPiratas:input_type -> sistema.Empty
	6,  // 7: sistema.GobiernoService.ConfirmarEntrega:input_type -> sistema.ConfirmarEntregaRequest
	7,  // 8: sistema.GobiernoService.ConsultarReputacion:input_type -> sistema.ReputacionRequest
	4,  // 9: sistema.GobiernoService.ObtenerEstadoGlobal:input_type -> sistema.Empty
	9,  // 10: sistema.GobiernoService.ReporteDeEstado:input_type -> sistema.EstadoRequest
	10, // 11: sistema.MarinaService.EntregarPirataMarina:input_type -> sistema.EntregaRequest
	4,  // 12: sistema.MarinaService.AlertaTraficoIlegal:input_type -> sistema.Empty
	11, // 13: sistema.SubmundoService.EntregarPirataSubmundo:input_type -> sistema.VentaRequest
	1,  // 14: sistema.GobiernoService.ObtenerListaPiratas:output_type -> sistema.ListaPiratas
	2,  // 15: sistema.GobiernoService.ConfirmarEntrega:output_type -> sistema.ResultadoOperacion
	8,  // 16: sistema.GobiernoService.ConsultarReputacion:output_type -> sistema.ReputacionResponse
	3,  // 17: sistema.GobiernoService.ObtenerEstadoGlobal:output_type -> sistema.EstadoGlobalResponse
	2,  // 18: sistema.GobiernoService.ReporteDeEstado:output_type -> sistema.ResultadoOperacion
	2,  // 19: sistema.MarinaService.EntregarPirataMarina:output_type -> sistema.ResultadoOperacion
	2,  // 20: sistema.MarinaService.AlertaTraficoIlegal:output_type -> sistema.ResultadoOperacion
	2,  // 21: sistema.SubmundoService.EntregarPirataSubmundo:output_type -> sistema.ResultadoOperacion
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sistema_proto_init() }
func file_sistema_proto_init() {
	if File_sistema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sistema_proto_rawDesc), len(file_sistema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_sistema_proto_goTypes,
		DependencyIndexes: file_sistema_proto_depIdxs,
		MessageInfos:      file_sistema_proto_msgTypes,
	}.Build()
	File_sistema_proto = out.File
	file_sistema_proto_goTypes = nil
	file_sistema_proto_depIdxs = nil
}
